### ISSUE TITLE
Add a reference for the "rg" program

### ISSUE THREAD

**Issue by ansell** [veorq/fca#3]
Could you add a reference in the readme for the "rg" program? This isn't my area of expertise, so it may be obvious to others but not sure what it refers to.

**Comment by ansell** [comment]
Is it just an alias for grep to reduce the number of bytes in the script?

**Comment by quininer** [comment]
[ripgrep](https://github.com/BurntSushi/ripgrep), I guess.

**Comment by ansell** [comment]
Thanks, that looks right. Changing fg to "grep -r" worked for me but that seems to be what ripgrep is designed for.

**Comment by veorq** [comment]
rg is much faster than grep, but yeah you can also use `grep -r` instead
